version: '2.0'

services:
    phpfpm:
        container_name: ttrss
        build: .
        volumes:
            - "${HOME}/public_html/ttrss:/var/www/html/ttrss"
        expose:
            - "9000"
        links:
            - ttrsdb:db
        restart: always
        depends_on:
            - ttrsdb

    ttrsdb:
        container_name: ttrssdb
        image: "postgres:alpine"
        volumes:
            - "ttrsdb_data:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: ttrssdb
            POSTGRES_PASSWORD: ttrssdb
        restart: always
        expose: 
            - "5432"

    fulltextrss:
        container_name: fulltextrss
        build: fulltextrss
        expose:
            - "9000"
        volumes:
            - "${HOME}/public_html/fulltextrss:/var/www/html/fulltextrss"

volumes:
    ttrsdb_data:
