version: '3.4'

services:
    phpfpm:
        container_name: ttrss
        build: .
        volumes:
            - "${HOME}/public_html/ttrss:/var/www/html/ttrss"
        expose:
            - "9000"
        restart: always
        depends_on:
            - ttrsdb
        networks:
            - caddy
            - default

    ttrsdb:
        container_name: ttrssdb
        image: "postgres:11-alpine"
        volumes:
            - "ttrsdb_data:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: ttrssdb
            POSTGRES_PASSWORD: ttrssdb
        restart: always
        expose: 
            - "5432"

    fulltextrss:
        container_name: fulltextrss
        build: fulltextrss
        expose:
            - "9000"
        volumes:
            - "${HOME}/public_html/fulltextrss:/var/www/html/fulltextrss"
        restart: always
        networks:
            - caddy
            - default

volumes:
    ttrsdb_data:

networks:
    caddy:
        external:
            name: caddy_default
